CREATE TABLE IF NOT EXISTS GAME (
  ID        INTEGER NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(50),
  STATUS    VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS MOVE (
  GAME_ID   INTEGER NOT NULL,
  ID        INTEGER NOT NULL,
  CELL      INTEGER NOT NULL,
  PRIMARY KEY(GAME_ID, ID),
  FOREIGN KEY(GAME_ID) REFERENCES GAME(ID)
);
