CREATE TABLE IF NOT EXISTS GAME (
  ID        INTEGER NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(50),
  STATUS    VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS MOVE (
  GAME_ID   INTEGER NOT NULL,
  ID        INTEGER NOT NULL,
  CELL      INTEGER NOT NULL,
  PRIMARY KEY(GAME_ID, ID),
  FOREIGN KEY(GAME_ID) REFERENCES GAME(ID)
);



CREATE TABLE IF NOT EXISTS TOURNAMENT (
  ID         INTEGER NOT NULL AUTO_INCREMENT,
  NAME       VARCHAR(50),
  START_DATE DATETIME,
  END_DATE   DATETIME,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS USER (
  ID        INTEGER NOT NULL,
  NAME      VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS VOTES
(
  USER_ID       INTEGER            NOT NULL,
  TOURNAMENT_ID INTEGER            NOT NULL,
  CHOICE        BOOLEAN            NOT NULL,

  PRIMARY KEY(USER_ID, TOURNAMENT_ID),
  FOREIGN KEY(TOURNAMENT_ID) REFERENCES TOURNAMENT(ID)
);
